name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        mvn clean 
        mvn deploy -Dregistry=https://maven.pkg.github.com/lilfrou -Dtoken=GH_TOKEN
